name: Commit Message Checker
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check-commit-message:
    uses: IsyFact/isyfact-standards/.github/workflows/commit_message_checker_template.yml@master