name: Dependency Review
on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  DependencyReview:
    uses: IsyFact/isyfact-standards/.github/workflows/dependency_review_template.yml@master