name: Dependabot Merger

on:
  push:
    branches:
      - 'development'

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    name: 'Dependabot Merge'
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    if: ${{ github.actor == 'dependabot(bot)' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
      - name: Approve and Merge PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"