name: Dependabot Auto Merge

on:
  pull_request:
    branches:
      - develop

jobs:
  DependabotAutoMerge:
    uses: IsyFact/isyfact-standards/.github/workflows/dependabot_auto_merge_template.yml@master
    secrets:
      GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}