name: Documentation Build

on:
  push:
    branches:
      - bugfix/IFS-3731_publishing_antora_documentation

jobs:
  DocsBuild:
    uses:  IsyFact/isy-github-actions-templates/.github/workflows/docs_build_template.yml@bugfix/IFS-3731_publishing_antora_documentation
    secrets:
      ANTORA_TRIGGER_TOKEN: ${{ secrets.ANTORA_TRIGGER_TOKEN }}
