name: Build Documentation

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Download Supplement Files
        run: curl https://github.com/IsyFact/isyfact.github.io/tree/0504ddec6394c49ca74cfd86428aaa322a19eba4/antora-ui/supplemental-ui

      - name: Install Antora CLI
        run: npm install -g @antora/cli @antora/site-generator

      - name: Run Antora
        run: antora isy-datetime-doc/antora-playbook.yml
