name: Compilieren und Tests
run-name: Build gestartet durch (${{ github.actor }})

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: JDK 21 einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Maven -> Compilieren, Tests
      run: mvn --batch-mode test --file pom.xml


