name: Compilieren und Tests
run-name: Build gestartet durch (${{ github.actor }})

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: JDK 21 einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Maven -> Compilieren, Tests
      run: mvn --batch-mode test --file pom.xml

    - name: Report
      run: |
        echo "| Modul | Testabdeckung |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
        
        COUNTER=0
        SUM=0
        for REPORT in $(find . -path \*target/site/jacoco/index.html); do
          MODULE=$(grep -o '<title>[^%].*</title>'  "$REPORT"| sed 's/<\/\?title>//g')
          COVERAGE=$(grep -o 'Total[^%]*%' "$REPORT" | sed 's/<.*>/ /; s/Total//; s/ //; s/%//')
          echo "| $MODULE | $COVERAGE % |" >> $GITHUB_STEP_SUMMARY
          COUNTER=$((COUNTER+1))
          SUM=$((SUM+COVERAGE))
        done
   

    - name: Erstelle Artefakt Test Reports
      uses: actions/upload-artifact@v4
      with:
        name:  Test-Reports
        path: |
          ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          ${{ github.workspace }}/**/target/surefire-reports/*.xml

  sonarcloud-scan:
    needs: [build]
    uses: IsyFact/isyfact-standards/.github/workflows/sonarcloud_scan_template.yml@feature/ISY-969-sonarcloud_integration_for_feature_workflow
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}