name: Maven Release
on:
  release:
    types: [released]

jobs:
  Build:
    uses: IsyFact/isyfact-standards/.github/workflows/maven_build_template.yml@master
    with:
      jdk-version: 21
      version: ${{ github.ref_name }}
      sonar-skip: true

  QualityGate:
    runs-on: ubuntu-latest
    needs: [ Build ]
    env:
      COMMIT_SHA: ${{ github.sha }}
      BRANCH_REF: master
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
    steps:
      - name: SonarCloud Quality Gate Check
        run: |
          ANALYSIS_ID=$( curl --silent "${SONAR_HOST_URL}/api/project_analyses/search?project=${SONAR_PROJECT_KEY}&branch=${BRANCH_REF/\//%2F}" | jq -r "first(.analyses[]|select(.revision==\"$COMMIT_SHA\").key)")

          if [[ -z $ANALYSIS_ID ]]; then
            echo "No Sonar Scan result found for commit $COMMIT_SHA"
            exit 1
          fi

          QG_STATUS=$(curl --silent "${SONAR_HOST_URL}/api/qualitygates/project_status?analysisId=${ANALYSIS_ID}" | jq -r ".projectStatus.status")

          if [[ $QG_STATUS == "OK" ]]; then
            echo "Quality Gate passed"
            exit 0
          elif [[ $QG_STATUS == "ERROR" ]]; then
            echo "Quality Gate failed"
            exit 1
          else
            echo "Could not find Quality Gate information for analysis id ${ANALYSIS_ID}"
            exit 1
          fi

  DependencyScan:
    uses: IsyFact/isyfact-standards/.github/workflows/maven_dependency_scan_template.yml@master
    with:
      jdk-version: 21
      snyk-reference: ${{ github.ref_name }}
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
      perform-scan: true
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  DeployMavenCentral:
    needs: [ QualityGate, DependencyScan ]
    uses: IsyFact/isyfact-standards/.github/workflows/maven_deploy_template.yml@master
    with:
      version: ${{ github.ref_name }}
      maven-opts: '-P centralRelease'
      deploy-server-id: ossrh
      sbom: true
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

  DependencyMonitor:
    needs: [ Deploy ]
    uses: IsyFact/isyfact-standards/.github/workflows/maven_dependency_scan_template.yml@master
    with:
      jdk-version: 21
      snyk-reference: $GITHUB_REF_NAME
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

