name: Erstelle JAR
run-name: Build gestartet durch (${{ github.actor }})

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: JDK 21 einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven -> Compilieren, Tests, Package
        run: mvn --batch-mode package --file pom.xml

      - name: Kopiere Artefakt JAR
        run:  cp target/*.jar artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/*.jar
